---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds.yaml
- namespace.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- webhooks.yaml

configurations:
- references.yaml
