---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bases/cert-manager
- issuer.yaml

configMapGenerator:
- name: letsencrypt
  files:
  - email=letsencrypt-email.txt

vars:
- name: LETSENCRYPT_EMAIL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: letsencrypt
  fieldref:
    fieldpath: data.email

configurations:
- references.yaml
