apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-qa
nameSuffix: -qa
commonLabels:
  stage: qa

resources:
- ../../../kustomize/traefik/
- ../../../kustomize/traefik-dashboard/
