---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: k8s.gcr.io/external-dns/external-dns
    newTag: v0.7.3

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
