---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bases/traefik
    repoURL: https://github.com/nicholasdille/k8s-gitops
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dashboard
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/traefik-dashboard
    repoURL: https://github.com/nicholasdille/k8s-gitops
    targetRevision: HEAD
