---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../overlays/cert-manager-letsencrypt
- issuer.yaml

secretGenerator:
- name: cloudflare
  files:
  - token=cloudflare-token.txt

configMapGenerator:
- name: cloudflare
  files:
  - email=cloudflare-email.txt
  - domain=cloudflare-domain.txt

vars:
- name: CLOUDFLARE_EMAIL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cloudflare
  fieldref:
    fieldpath: data.email
- name: CLOUDFLARE_DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cloudflare
  fieldref:
    fieldpath: data.domain

configurations:
- references.yaml
