---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: argocd.dille.io
      http:
        paths:
          - backend:
              serviceName: argocd-server
              servicePort: 80
